apiVersion: v1
kind: Service
metadata:
  name: http-echo-service
spec:
  type: LoadBalancer
  selector:
    app: http-echo
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP